### ISSUE TITLE
Erro with custom retrained model

### ISSUE THREAD

**Issue by josete89** [kakugawa/MetalCNNWeights#1]
Hi,

I'm adding a new layer in the inception v3 model and I try to create the files for apple (using tensor flow stuff goes ok)But I'm getting this error

Traceback (most recent call last):
  File "./convert.py", line 349, in <module>
    main()
  File "./convert.py", line 346, in main
    softmax_write(output_dir, dat_dir, sess)
  File "./convert.py", line 154, in softmax_write
    weights = sess.graph.get_tensor_by_name('softmax/weights:0').eval()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2607, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2458, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2500, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'softmax/weights:0' refers to a Tensor which does not exist. The operation, 'softmax/weights', does not exist in the graph."

**Comment by kakugawa** [comment]
The script doesn't inspect your graph and auto-adjust it's conversion. It just demonstrates how to convert the standard Inception v3 model.

It should be straightforward to read the code and modify it for your graph though.

**Comment by josete89** [comment]
:) thanks. I modified the necessary stuff, I printed the graph -> 
`'final_training_ops/weights/final_weights', u'final_training_ops/weights/final_weights/read', u'final_training_ops/biases/final_biases', u'final_training_ops/biases/final_biases/read', u'final_training_ops/Wx_plus_b/MatMul', u'final_training_ops/Wx_plus_b/add', u'final_result'`
 and  I modified this
` # read
    weights = sess.graph.get_tensor_by_name('final_training_ops/weights/final_weights:0').eval()
    biases  = sess.graph.get_tensor_by_name('final_training_ops/biases/final_biases:0' ).eval()`

and it's generating the file but the size it's 25kb compared with the normal one 8.7mb and it's chasing the app. I really appreciate your help :)

**Comment by kakugawa** [comment]
Do you have a copy of the model? And which app is it crashing?

**Comment by josete89** [comment]
here is the model -> https://www.dropbox.com/s/7vtllf07z00mrp9/retrained_graph.pb?dl=0
An iOS app which is loading the model :)
